import type { Metadata } from "next";
import "./globals.css";

// Providers
import { Providers } from "@/shared/providers";

// Widgets
import Header from "@/widgets/Header";

export const metadata: Metadata = {
  title: "Resurrection",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="relative">
        <Providers>
          <Header/>
          {children}
          <div id="modal"></div>
        </Providers>
      </body>
    </html>
  );
}
