import { Suspense } from "react";
import type { Metadata } from "next";
import "./globals.css";

// Providers
import { Providers } from "@/shared/providers";

// Requests
import { fetchCategories } from "@/entities/category/api/categoryApi";

// Widgets
import Header from "@/widgets/Header";
import Footer from "@/widgets/Footer";

export const metadata: Metadata = {
  title: "Fiesta Shop",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Getting categories
  const categories = await fetchCategories()
  
  return (
    <html lang="en">
      <body className="relative">
        <Providers categories={categories}>
          <Header/>
          <Suspense fallback={<div>Downloading...</div>}>
            <main className="!py-5">
              {children}
            </main>
          </Suspense>
          <Footer/>
          <div id="modal"></div>
        </Providers>
      </body>
    </html>
  )
}
